# Generated by Django 5.0.6 on 2024-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
